INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'admin01', 'Get AWS Certified', CURRENT_DATE(), FALSE);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'admin01', 'Get Azure Certified', CURRENT_DATE(), FALSE);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'admin01', 'Get GCP Certified', CURRENT_DATE(), FALSE);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'admin01', 'Learn to swim', CURRENT_DATE(), FALSE);